<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="racecar">
  <xacro:arg name="use_nominal_extrinsics" default="false" />
  <xacro:include filename="$(find f1tenth_description)/urdf/_d435i.urdf.xacro"/>
  

  <xacro:property name="wheelbase" value="0.3302" />
  <xacro:property name="width" value="0.2032" />
  <xacro:property name="height" value="0.1" />
  <xacro:property name="ground_offset" value="0.04" />
  <xacro:property name="wheel_radius" value="0.0508" />
  <xacro:property name="wheel_length" value="0.0381" />
  <xacro:property name="laser_distance_from_base_link" value="0.275" />
  <xacro:property name="laser_height" value="0.05" />
  <xacro:property name="laser_radius" value="0.026" />
  <xacro:property name="car_name" value="ego_racecar" />

  <material name="black">
    <color rgba="0.2 0.2 0.2 1."/>
  </material>

  <material name="blue">
    <color rgba="0.3 0.57 1. 1."/>
  </material>
<!-- ================================================================== BASE ================================================================== -->
  <link name="base_link">
    <visual>
      <origin xyz="${wheelbase/2} 0 ${ground_offset+height/2}"/>
      <geometry>
        <box size="${wheelbase} ${width} ${height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>
<!-- ================================================================== LASER ================================================================== -->
  <joint name="base_to_laser_link" type="fixed">
    <parent link="base_link"/>
    <child link="laser_link"/>
    <origin xyz="${laser_distance_from_base_link} 0 ${ground_offset+height+(laser_height/2)}"/>
  </joint>

  <link name="laser_link">
    <visual>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_height}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>
<!-- ================================================================== RARE LEFT WHEEL ================================================================== -->
  <joint name="base_to_back_left_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="back_left_wheel"/>
    <origin xyz="0 ${(wheel_length+width)/2} ${wheel_radius}" rpy="${pi/2} 0.0 0.0"/>
    <axis xyz="0.0 0.0 1.0"/>
  </joint>

  <link name="back_left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black"/>
      <origin rpy="0 0 0"/>
    </visual>
  </link>
<!-- ================================================================== RARE RIGHT WHEEL ================================================================== -->
  <joint name="base_to_back_right_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="back_right_wheel"/>
    <origin xyz="0 ${-(wheel_length+width)/2} ${wheel_radius}" rpy="${pi/2} 0.0 0.0"/>
    <axis xyz="0.0 0.0 1.0"/>
  </joint>

  <link name="back_right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black"/>
      <origin rpy="0 0 0"/>
    </visual>
  </link>
<!-- ================================================================== FRONT LEFT WHEEL STEER ================================================================== -->
  <link name="front_left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black"/>
      <origin rpy="0.0 0.0 0.0"/>
    </visual>
  </link>

  <joint name="front_left_hinge_to_wheel" type="continuous">
    <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
    <parent link="front_left_hinge"/>
    <child link="front_left_wheel"/>
    <axis xyz="0.0 0.0 1.0"/>
  </joint>

  <link name="front_left_hinge">
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="0.001" length="0.01"/>
      </geometry>
    </visual>
  </link>
  
  <joint name="base_to_front_left_hinge" type="revolute">
    <parent link="base_link"/>
    <child link="front_left_hinge"/>
    <origin xyz="${wheelbase} ${(wheel_length+width)/2} ${wheel_radius}"/>
    <axis xyz="0.0 0.0 1.0"/>
    <limit lower="0.52" upper="-0.52" effort="10" velocity="2.5"/>
  </joint>

<!-- ================================================================== FRONT RIGHT WHEEL STEER ================================================================== -->
  <joint name="base_to_front_right_hinge" type="revolute">
    <parent link="base_link"/>
    <child link="front_right_hinge"/>
    <origin xyz="${wheelbase} ${-(wheel_length+width)/2} ${wheel_radius}"/>
    <axis xyz="0.0 0.0 1.0"/>
    <limit lower="0.52" upper="-0.52" effort="10" velocity="2.5"/>
  </joint>

  <link name="front_right_hinge">
      <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="0.001" length="0.01"/>
      </geometry>
    </visual>
  </link>

  <joint name="front_right_hinge_to_wheel" type="continuous">
    <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
    <parent link="front_right_hinge"/>
    <child link="front_right_wheel"/>
    <axis xyz="0.0 0.0 1.0"/>
  </joint>

  <link name="front_right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black"/>
      <origin rpy="0 0 0"/>
    </visual>
  </link>
<!-- ================================================================== CAMERA ================================================================== -->
  <link name="cam_link" />
  <xacro:sensor_d435i parent="cam_link" use_nominal_extrinsics="$(arg use_nominal_extrinsics)">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:sensor_d435i>
  <joint name="base_to_cam_link" type="fixed">
    <parent link="base_link"/>
    <child link="cam_link"/>
    <origin xyz="${laser_distance_from_base_link} 0 ${ground_offset+height+(laser_height)}"/>
  </joint>

</robot>